services:
  bb:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BB_APP_VERSION: ${BB_APP_VERSION}
        PI_VERSION: ${PI_VERSION}

    restart: unless-stopped

    environment:
      HOME: /data
      BB_DATA_DIR: /data/.bb
      BB_SERVER_BIND_HOST: "0.0.0.0"
      BB_APP_URL: ${BB_APP_URL}

    volumes:
      - bb_data:/data

    labels:
      - "traefik.http.routers.bb.middlewares=bb-auth"
      - "traefik.http.middlewares.bb-auth.basicauth.users=admin:${BB_AUTH_HASH}"


volumes:
  bb_data:
